export const cards = [
  { 'name': 'Ace of Cups',
    'imgpath': 'img/cups01.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Two of Cups',
    'imgpath': 'img/cups02.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Three of Cups',
    'imgpath': 'img/cups03.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Four of Cups',
    'imgpath': 'img/cups04.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Five of Cups',
    'imgpath': 'img/cups05.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Six of Cups',
    'imgpath': 'img/cups06.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Seven of Cups',
    'imgpath': 'img/cups07.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Eight of Cups',
    'imgpath': 'img/cups08.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Nine of Cups',
    'imgpath': 'img/cups09.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Ten of Cups',
    'imgpath': 'img/cups10.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Page of Cups',
    'imgpath': 'img/cups11.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Knight of Cups',
    'imgpath': 'img/cups12.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Queen of Cups',
    'imgpath': 'img/cups13.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'King of Cups',
    'imgpath': 'img/cups14.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Ace of Swords',
    'imgpath': 'img/swords01.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Two of Swords',
    'imgpath': 'img/swords02.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Three of Swords',
    'imgpath': 'img/swords03.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Four of Swords',
    'imgpath': 'img/swords04.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Five of Swords',
    'imgpath': 'img/swords05.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Six of Swords',
    'imgpath': 'img/swords06.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Seven of Swords',
    'imgpath': 'img/swords07.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Eight of Swords',
    'imgpath': 'img/swords08.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Nine of Swords',
    'imgpath': 'img/swords09.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Ten of Swords',
    'imgpath': 'img/swords10.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Page of Swords',
    'imgpath': 'img/swords11.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Knight of Swords',
    'imgpath': 'img/swords12.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Queen of Swords',
    'imgpath': 'img/swords13.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'King of Swords',
    'imgpath': 'img/swords14.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Ace of Wands',
    'imgpath': 'img/wands01.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Two of Wands',
    'imgpath': 'img/wands02.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Three of Wands',
    'imgpath': 'img/wands03.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Four of Wands',
    'imgpath': 'img/wands04.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Five of Wands',
    'imgpath': 'img/wands05.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Six of Wands',
    'imgpath': 'img/wands06.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Seven of Wands',
    'imgpath': 'img/wands07.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Eight of Wands',
    'imgpath': 'img/wands08.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Nine of Wands',
    'imgpath': 'img/wands09.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Ten of Wands',
    'imgpath': 'img/wands10.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Page of Wands',
    'imgpath': 'img/wands11.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Knight of Wands',
    'imgpath': 'img/wands12.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Queen of Wands',
    'imgpath': 'img/wands13.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'King of Wands',
    'imgpath': 'img/wands14.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Ace of Pentacles',
    'imgpath': 'img/pents01.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Two of Pentacles',
    'imgpath': 'img/pents02.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Three of Pentacles',
    'imgpath': 'img/pents03.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Four of Pentacles',
    'imgpath': 'img/pents04.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Five of Pentacles',
    'imgpath': 'img/pents05.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Six of Pentacles',
    'imgpath': 'img/pents06.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Seven of Pentacles',
    'imgpath': 'img/pents07.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Eight of Pentacles',
    'imgpath': 'img/pents08.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Nine of Pentacles',
    'imgpath': 'img/pents09.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Ten of Pentacles',
    'imgpath': 'img/pents10.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Page of Pentacles',
    'imgpath': 'img/pents11.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Knight of Pentacles',
    'imgpath': 'img/pents12.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'Queen of Pentacles',
    'imgpath': 'img/pents13.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'King of Pentacles',
    'imgpath': 'img/pents14.jpg',
    'keywords': "",
    'light': "",
    'shadow': "",
    'focus_relationships': "",
    'focus_work': "",
    'focus_spirituality': "",
    'focus_personalgrowth': "",
    'focus_fortunetelling': ""
  },
  { 'name': 'The Fool',
    'imgpath': 'img/tarot-0-fool.jpg',
    'keywords': 'Freedom, faith, inexperience, innocence',
    'light': 'Freeing yourself from limitation. Expressing joy and youthful vigor. Being open-minded. Taking a leap of faith. Attuning yourself to your instincts. Being eager or curious. Exploring your potential. Embracing innovation and change.',
    'shadow':'Being gullible and naive. Taking unnecessary risks. Failing to be serious when required. Being silly or distracted. Lacking experience. Failing to honor well-established traditions and limits. Behaving inappropriately.',
    'focus_relationships': "There's a reason we say we 'fall' in love! Each new romance makes us as giddy as a total beginner. Don't allow old habits to smother opportunities for growth. You can break rules without resorting to rash action and you don't have to be in control all the time.",
    'focus_work': "Leap over limits. Don't waver; now's the time to jump, even if you don't have all the facts in hand. Remember that once, every new direction was just another crazy idea. Be prepared, though. Later, your results will determine whether others deem you clever or crazy.",
    'focus_spirituality': "You are old and young, wise and inexperienced. Life is a cycle of cycles; find your place in the dance and start dancing. Reinvention is the key to transformation. See who you are, but acknowledge, too, the person you can be. Grace abounds; embrace it. Consider Zen meditation.",
    'focus_personalgrowth': "Without falling for every scheme that comes your way, you can cultivate an openness to life. What are your limits? What boundaries define you? What might happen if you step outside those definitions? With eyes wide open, expand your world today.",
    'focus_fortunetelling': "Watch for new projects and new beginnings. Prepare to take something on faith. Something new comes your way; go for it."
  },
  { 'name': 'The Magician',
    'imgpath': 'img/tarot-1-magician.jpg',
    'keywords': "Capability, empowerment, activity",
    'light': "Taking appropriate action. Receiving guidance from a higher power. Becoming a channel of divine will. Expressing masculine energy in appropriate and constructive ways. Being yourself in every way.",
    'shadow': "Inflating your own ego. Abusing talents. Manipulating or deceiving others. Being too aggressive. Using cheap illusions to dazzle others. Refusing to invest the time and effort needed to master your craft. Taking shortcuts.",
    'focus_relationships': "A relationship should empower you. Does yours generate positive change in your life? Do you feel happier and more fulfilled? A relationship that supports your goals is to be valued; a relationship that doesn't must be changed or cast aside.",
    'focus_work': "Exercise whatever authority you have. With the right resources, you'll succeed. But not everyone who appears empowered really is. With an eye toward growth, seek allies who focus on steak, not sizzle. Be a mentor ... or find one. Deploy tools and resources against well-defined goals.",
    'focus_spirituality': "If others were to see you and your life as an expression of the Divine, what would their impression of the Divine be? How can you improve that perception? How can you better dedicate yourself to being a channel for positive energy in the world?",
    'focus_personalgrowth': "Asserting yourself can be an important step toward wholeness. When your work or life experience has given you special insights or talents, shrug off self-doubt and apply them fearlessly. Act confidently, and feelings of confidence will follow.",
    'focus_fortunetelling': "A powerful man may play a role in your day. Your current situation must be seen as one element of a much larger plan."
  },
  { 'name': 'The High Priestess',
    'imgpath': 'img/tarot-2-high-priestess.jpg',
    'keywords': "Intuition, reflection, purity, initiation",
    'light': "Listening to your feelings and intuitions. Exploring unconventional spirituality. Keeping secrets. Being receptive. Reflecting instead of acting. Observing others. Preserving purity.",
    'shadow': "Being aloof. Obsessing on secrets and conspiracies. Rejecting guidance from spirit or intuition. Revealing all. Ignoring gut feelings. Refusing to become involved, even when involvement is appropriate.",
    'focus_relationships': "Your heart is your best source of information now; listen to it. Set, communicate, and respect sexual limits. Don't tell everything you know; one element of attraction is mystery. Still, don't be a puzzle; communicate your needs and the reasons for them. Watch and learn.",
    'focus_work': "Play your cards close to the vest. Reveal your insights to a chosen few. Rather than take rash action now, keep still and observe. Hold your tongue and learn by listening. Listen to your gut instincts. When the time comes for action, you'll know.",
    'focus_spirituality': "The unconventional image of a papess recalls the legend of the heretical, cross-dressing Pope Joan, whose true gender was revealed when she unexpectedly gave birth. Consider alternative spiritual paths or nontraditional applications of your familiar faith.",
    'focus_personalgrowth': "Learning to listen can be the most difficult lesson of all. Invest energy in the transformational discipline of silence. Disengaging from the drive to respond will free you to reflect. As an observer, you will see patterns participants will overlook.",
    'focus_fortunetelling': "A mysterious woman arrives. A sexual secret may surface. Someone knows more than he or she will reveal."
  },
  { 'name': 'The Empress',
    'imgpath': 'img/tarot-3-the-empress.jpg',
    'keywords': "Fertility, productivity, ripeness, nurturing",
    'light': "Nurturing yourself and others. Bearing fruit. Celebrating your body. Bearing (literal or figurative) children. Reveling in luxury. Mothering those around you in positive ways. Enjoying your sexuality. Getting things done.",
    'shadow': "Overindulging. Being greedy. Smothering someone with attention. Debilitating someone by being overprotective. Inhibiting productivity by obsessing on productivity. Being overcome by addictive behavior.",
    'focus_relationships': "Without going overboard, revel in your sensuality. Take care you don't produce more than you intended; the moment is pregnant with possibility. Be lavish with demonstrations of affection. Watch for what a friend or partner needs, and then supply it in abundance.",
    'focus_work': "Now is the time to get things done. Wrap up projects. Ask for resources. Meet deadlines. Move ahead. During this time of growth and expansion, be sure you have the skills and training you need. In the meantime, don't mistake a headlong rush for focused, verifiable progress.",
    'focus_spirituality': "Women are the figurative and literal door to this world. This moment, too, can be a door for youÑa threshold you cross into a new awareness. Watch for physical ways to express your spiritual insights. Reconnect with nurturing, feminine images of divinity, including nature.",
    'focus_personalgrowth': "Your attitudes toward women (and your insights into your own feminine qualities) are likely rooted in early experiences. How can you emulate the best female role models you've encountered? How can you transcend female influences that harm or hold you back?",
    'focus_fortunetelling': "Pregnancy is in the cards. An opportunity to be involved in luxurious sexuality is coming. Beware a tendency toward addiction."
  },
  { 'name': 'The Emperor',
    'imgpath': 'img/tarot-4-the-emperor.jpg',
    'keywords': "Authority, regulation, direction, structure",
    'light': "Exercising authority. Defining limits. Directing the flow of work. Communicating clear guidelines. Being in control of yourself and others. Tempering aggressive masculinity with wisdom and experience.",
    'shadow': "Micromanaging. Crushing the creativity of others with a rigid, iron-fisted approach. Insisting on getting your own way. Assuming a dictatorial mindset. Using overt force to achieve your goals and maintain order.",
    'focus_relationships': "Without becoming false or deceptive, you can regulate your feelings and reactions. Beware the need to always be in control; a healthy relationship incorporates a fair division of labor. Be on the lookout for subtle (and not-so-subtle) efforts to wear the pants in the relationship.",
    'focus_work': "Efficient groups depend on centralized control. Seek ways to direct the flow without micromanaging the process. Encourage leaders (including yourself) to step up to the plate and embrace their obligations. Control what you can; don't worry about the rest.",
    'focus_spirituality': "The stereotypical view of religion casts organized faith in restrictive terms. Rather than be constrained by structure, consider how structure and discipline might enhance your spiritual experience. Seek guidance and direction from those who have walked the path before you.",
    'focus_personalgrowth': "In what ways do your attitudes toward authority seem to be shaped by your relationship with your father? A mature person recognizes that structure and authority are a requirement of civilization. Some resist purely out of habit or stubbornness; when you buck the system, be sure you have good reason to do so. ",
    'focus_fortunetelling': "A father figure arrives. A new employer or authority figure will give you orders. Expect discipline or correction in the near future."
  },
  { 'name': 'The Hierophant',
    'imgpath': 'img/tarot-5-the-hierophant.jpg',
    'keywords': "Guidance, knowledge, revelation, belief",
    'light': "Teaching or guiding others. Searching for the truth. Asking for guidance from a higher power. Acknowledging the wisdom and experience of others. Taking vows. Engaging in heartfelt rituals. Volunteering.",
    'shadow': "Using experience as a means of manipulating or misguiding others. Being dogmatic. Favoring tradition over what is expedient or necessary. Going through the motions of empty rituals. Concealing wisdom. Restricting access to spiritual truths or the gods.",
    'focus_relationships': "A relationship should be more than just going through the motions. Seek the deeper meaning of small gestures and daily chores. Emphasize signs that those involved have real faith in the partnership. If necessary, seek guidance from a spiritual leader or counselor. ",
    'focus_work': "Seek training or a mentor, particularly if you are having difficulty understanding a complex assignment or when adjusting to new professional surroundings. See your daily work as an expression of your faith. Take traditional routes instead of innovative, unproven measures.",
    'focus_spirituality': "See familiar spiritual symbols in a new light by pursuing a deeper understanding of them. If you're a lone practitioner, consider the value of joining a like-minded group or learning from a worthy teacher. What are the larger truths behind the rituals or stories you've learned?",
    'focus_personalgrowth': "In time, everyone must deal with conflicts between experience and faith. Where do you find your personal center? Values dictate behavior, so work to define what you truly believe in. Don't shy away from the big questions, but be wary of gurus bearing quick answers.",
    'focus_fortunetelling': "Expect to be caught in a misdeed and punished accordingly. Pray for forgiveness and confess wrongdoings. A more experienced man, spiritual leader, or father figure will come into your life."
  },
  { 'name': 'The Lovers',
    'imgpath': 'img/tarot-6-the-lovers.jpg',
    'keywords': "Love, passion, unity, choice",
    'light': "Being in love. Showing your love to others. Expressing passion or romantic feelings. Aligning yourself with groups or like-minded others. Bringing people together. Making well-informed decisions.",
    'shadow': "Debilitating passion. Allowing an unhealthy desire for love to motivate destructive behavior. Disrupting unity. Working against the best interests of those who care about you. Ill-informed decisions.",
    'focus_relationships': "This is a time to celebrate unity, love, and romance in all its forms. Souls are coming together, and a unique opportunity exists for people to enjoy an unusual degree of interdependence and cooperation. Let your heart guide your choices today.",
    'focus_work': "Call group meetings, pursue mergers, and find solid business partners during this rare opportunity for successful cooperation. Pay special attention to opportunities to supply what others need. Lay a foundation for future success by watching for team members with skills you lack. Make choices based on what you truly enjoy doing.",
    'focus_spirituality': "Open yourself to new and diverse spiritual experiences. See opportunities to love others (even romantically) as chances to be a channel for divine love. Every small blessing you receive is an expression of universal love; give thanks and embrace what life brings you.",
    'focus_personalgrowth': "Now is a good time to deal with outstanding issues related to sexuality and relationships. Rather than be overwhelmed with Hollywood-style passion, consider the extent to which your qualities might be balanced or enhanced by those of your potential partner. In other areas, find your passion and pursue it.",
    'focus_fortunetelling': "A new personal or professional relationship blossoms. Sexual opportunities abound. Unexpectedly, a friend becomes a lover."
  },
  { 'name': 'The Chariot',
    'imgpath': 'img/tarot-7-the-chariot.jpg',
    'keywords': "Advancement, victory, triumph, success",
    'light': "Breaking through barriers. Moving forward with confidence and authority. Reaching the pinnacle of success. Basking in the glory of achievement. Guiding an effort to total victory. Establishing yourself as a worthy leader.",
    'shadow': "Resting on laurels. Riding roughshod over the feelings or expectations of others. Focusing more on past successes than future opportunities. Failing to rein in impulsive behavior.",
    'focus_relationships': "Moving forward to mutual victory requires trust and cooperation. If you have this already, depend on it during an upcoming challenge. If you lack it, consider what choices have prevented forming this kind of bond. Don't rest on your laurels; successful romance is an ongoing commitment.",
    'focus_work': "What do you need to move forward? Now is the time to summon resources and plan for future success. Past successes might not be an indicator of current value. Remember that employers tend to ask 'What have you done for me lately?' Work accordingly.",
    'focus_spirituality': "Celebrate spiritual achievement, but be aware that a sense of having arrived can be the first step toward disastrous vanity. The goal is not to be a guru, but to achieve balance and stability. As you make progress, extend a helping hand to others who still await their chariot moment.",
    'focus_personalgrowth': "Reaching a new plane of maturity is exciting, so some celebration is in order. Every ending, though, is a new beginning; keep an eye fixed on further growth. Having reached the limits of mundane success, it's time to work on deeper transformation.",
    'focus_fortunetelling': "Victory is a certainty. Move ahead with all plans. Beware the jealousy of others."
  },
  { 'name': 'Strength',
    'imgpath': 'img/tarot-8-strength.jpg',
    'keywords': "Discipline, boldness, self-discipline, power, vitality",
    'light': "Imposing restrictions on yourself for your own benefit. Bringing your passions under the control of reason. Resisting impulses that work against your best interests. Taking bold action.",
    'shadow': "Indulging weakness, even when you know it will damage your health and happiness. Languishing in addiction. Allowing your instincts to tame and conquer you. Failing to take a stand when necessary.",
    'focus_relationships': "You're in control. You can't tame others, but you can rein yourself in. Watch for old habits or weaknesses to surface, and use your wits to avoid upcoming pitfalls.",
    'focus_work': "Emotions and distractions can hinder progress. Identify the cause of dissention and take steps to moderate it. Allow people (including yourself) to do what they do best. An objective perspective yields more effective action.",
    'focus_spirituality': "The spirit is willing, but the flesh is weak. Your own willpower may not be strong enough to resist the temptations that come your way. (That's okay; you're human.) Turn challenges over to a higher power, and allow yourself to be led.",
    'focus_personalgrowth': "Identify problematic habits and unhealthy tendencies, and weigh their overall impact on your life. Consider, too, the value of leaving these behind for healthier options. A good measure of maturity is the ability to forgo immediate gratification to reap benefits later.",
    'focus_fortunetelling': "Your self-control will be tested. A woman will seek to change her partner or lover. You are a strong, capable person."
  },
  { 'name': 'The Hermit',
    'imgpath': 'img/tarot-9-hermit.jpg',
    'keywords': "Solitude, experience, stillness, withdrawal",
    'light': "Becoming or seeking out a guru. Going on a retreat. Recharging spiritual or creative batteries. Lighting the way for those with less experience. Stepping back to gain perspective.",
    'shadow': "Being a loner. Fearing contact with others. Becoming a know-it-all. Inflating claims of expertise. Hiding your skills and talents out of fear of unworthiness.",
    'focus_relationships': "Don't be afraid of being alone. Even the closest companions need some time apart. Being involved in a partnership does not eliminate your need to be your own person. To better please others, first learn how to please yourself.",
    'focus_work': "Sometimes, you have to close the door, forward calls to voice mail, and shut down your email client to get things done. Demand the space and time you need to get your assignment done. If you're overwhelmed, consider bringing in a consultant or an experienced aid.",
    'focus_spirituality': "Learn to be still. Doing so is a challenge in today's hurly-burly world, but the skill offers many benefits. Focus on meditation; condition yourself to slow your thoughts and lower your blood pressure with a few measured breaths. Daily practice will make a huge difference in the quality of your life.",
    'focus_personalgrowth': "To be the best you can be, you must know who you really are. Reject the definitions others project on you. Search within. What do you really value? What do you really want to achieve? Empower yourself by embracing yourself, warts and all.",
    'focus_fortunetelling': "A period of loneliness begins. One partner in a relationship departs. A search for love or money proves fruitless."
  },
  { 'name': 'Wheel of Fortune',
    'imgpath': 'img/tarot-10-wheel-of-fortune.jpg',
    'keywords': "Luck, randomness, cycles, karma, fate, revolution",
    'light': "Allowing events to unfold. Seeing the larger pattern in everyday events. Trusting your luck. Watching for cycles. Believing that what goes around, comes around.",
    'shadow': "Losing money gambling. Refusing to do your part to bring a plan to fruition. Taking a fatalistic approach to life. Fighting the natural course of events.",
    'focus_relationships': "You can't plan every moment. Be spontaneous. Rather than strive for control, let go of the reins and see where the relationship goes. Check your behaviors. Are you reliving mistakes of the past?",
    'focus_work': "Feeling a little de[as]ja[ag]-vu? Return to old files; new solutions might be lying dormant there. Ask yourself what this new opportunity has in common with older challenges. In analysis, take into account all influences, including those beyond your control.",
    'focus_spirituality': "Behold the delicate machinery of heaven! As you watch events unfold, keep your perspective. What seems impossible to understand today will make sense with the passing of time. Look for the larger patterns.",
    'focus_personalgrowth': "The actions you take today will influence your reality for days and years to come. Making wise choices now can free you from the unpleasant business of enduring repercussions further down the road.",
    'focus_fortunetelling': "Some events are in the hands of heaven. You've lived through this before. What happened then?"
  },
  { 'name': 'Justice',
    'imgpath': 'img/tarot-11-justice.jpg',
    'keywords': "Balance, law, fairness, objectivity",
    'light': "Making an objective decision. Weighing an issue carefully before taking action. Appropriately scaling your reaction to a situation. Getting all the facts. Considering evidence. Deliberating.",
    'shadow': "Delivering harsh criticism. Obsessing on rules and regulations. Playing by the book even when it is destructive or counterproductive to do so. Confusing snap decisions with timely action. Playing favorites.",
    'focus_relationships': "Relationships are rarely 50/50 propositions, but the closer you come to an even division of responsibility, the better. What do you really need to be satisfied? Knowing your standards empowers you to evaluate your feelings more clearly.",
    'focus_work': "Work toward a more equitable division of labor. Learn to delegate. Evaluate your own work using the same standard you bring to bear on the work of others. Know what matters most, and prioritize accordingly.",
    'focus_spirituality': "In all things, seek balance. When faced with a decision, quiet your mind and allow your heart to weigh the moment. Trust in the law of karma; avoid personal efforts to mete out universal justice.",
    'focus_personalgrowth': "Everyone faces limitations of some kind. Learn your own limits. Rather than allow them to define you, use what you know to better position yourself for success. Learn when to say yes; know when to say no.",
    'focus_fortunetelling': "A legal verdict will be rendered soon. Someone is making a decision. You need to get the facts."
  },
  { 'name': 'The Hanged Man',
    'imgpath': 'img/tarot-12-the-hanged-man.jpg',
    'keywords': "Enlightenment, sacrifice, perspective, suspension, reversals",
    'light': "Seeing growth opportunities in unpleasant events. Experiencing a dramatic change in personal perspective. Making the best of an unforeseen change in your life or work. Suspending disbelief. Making sacrifices.",
    'shadow': "Being untrue to yourself and your values. Refusing to make sacrifices when appropriate. Refusing to adapt to new situations. Blaming others. Profiting at the expense of others.",
    'focus_relationships': "What doesn't move forward isn't growing. If you're hanging by a thread, it might be time to grab the scissors. If you can learn from what's not working, do so, but don't equate learning with having to stay.",
    'focus_work': "Occasionally, no amount of effort will move a project to completion; progress simply isn't the cards, despite your best efforts. Learn from setbacks; turn disappointment into opportunity.",
    'focus_spirituality': "Sometimes the best action is no action at all. Suspend your need to have a hand in things. Consider, too, the value of small sacrifices. What you give away will come back to you greatly multiplied.",
    'focus_personalgrowth': "One sign of maturity is your ability to deal effectively with the unexpected. Rather than be decimated, look for the lesson. If you're true to your own values, no disaster will get the best of you.",
    'focus_fortunetelling': "A traitor is revealed. One of your friends is working against you. Change your ways or suffer the consequences."
  },
  { 'name': 'Death',
    'imgpath': 'img/tarot-13-death.jpg',
    'keywords': "Ending, conclusion, transition, passage, departure",
    'light': "Bringing an unpleasant phase of life to an end. Recognizing and celebrating the conclusion of something. Putting bad habits to rest. Becoming a new person. Leaving one person, place, or thing for another. Letting go.",
    'shadow': "Obsessing on death and dying. Refusing to give up old habits or unhealthy relationships. Insisting that everything and everyone should stay the same forever. Failing to take good care of yourself.",
    'focus_relationships': "Identify what's not working and put it behind you. Take stock, too, of the relationship itself. Dying flames can be rekindled with mutual effort, but embrace an ending if, in fact, an ending is what's best for you. Poets used to call orgasm the 'little death,' so, at times, this card can also point to a consummated relationship!",
    'focus_work': "Close out lingering projects and tie up loose ends. Now is a good time to consider all your options, including the possibility of moving on. Alternatively, you could put an end to feelings of unrest by deciding, once and for all, to stay put. Do what's best for you.",
    'focus_spirituality': "Spiritual scribes write of 'dying to the world' realizing that the physical world and its concerns are illusory at best. For you, the Death card is a reminder to focus on what really matters. Alternatively, the card can suggest a need to contact or honor your ancestors.",
    'focus_personalgrowth': "Grasping the short, fleeting nature of life is one of life's hardest and most sobering lessons. Acknowledging your own impermanence can help you live your life more fully.",
    'focus_fortunetelling': "A relationship or illness ends suddenly. Limit travel and risk-taking. General gloom and doom."
  },
  { 'name': 'Temperance',
    'imgpath': 'img/tarot-14-temperance.jpg',
    'keywords': "Blending, synthesis, mediation, combination, harmony",
    'light': "Bringing opposites together. Moderating your actions or emotions. Finding middle ground. Reaching compromises. Synthesizing solutions that please everyone involved. Using the old to make something new.",
    'shadow': "Going to extremes. Disrupting group efforts. Ignoring healthy approaches to life. Becoming an addict. Practicing gluttony. Tearing something or someone apart. Breaking alliances.",
    'focus_relationships': "Set superficial relationships aside. Pursue trust and deep intimacyÑthe subtle blending of two people into one. Bring people together. Commit to introductions, parties, or gatherings. Seek out groups.",
    'focus_work': "Many hands make work easier. Call meetings. Get input from every level at every step. If everyone has a hand in defining an effort, then everyone will feel ownership and investment. Moderate your tendency toward all-or-nothing work habits.",
    'focus_spirituality': "Some spiritual advisors recommend extreme practices, from fasting to abstinence, as a means of boosting spiritual awareness. Consider the potential value of moderation in all things. You can value what is right here, right now, without craving more or surpassing healthy limits.",
    'focus_personalgrowth': "Young people want to toss out tradition and forge ahead. Older people are more conservative. Between these extremes lies a healthier middle ground. Define the polarities and then ask, 'What lies between?'",
    'focus_fortunetelling': "Someone's using drugs or alcohol to excess. It's time to get back on that diet."
  },
  { 'name': 'The Devil',
    'imgpath': 'img/tarot-15-the-devil.jpg',
    'keywords': "Shadow, materialism, bondage, delusion",
    'light': "Appreciating the luxuries that life has to offer. Being comfortable in your own skin. Enjoying your sexuality. Splurging on an expensive personal item. Embracing the fact that everyone has a darker side. Dealing with unhealthy impulses in healthy ways.",
    'shadow': "Putting excessive emphasis on appearances. Always wanting more. Valuing possessions more than people or relationships. Allowing base instincts to govern your life. Being selfish. Attributing your own dark impulses to outside forces or other people.",
    'focus_relationships': "Avoid the temptation to blame everything on everyone else; own your own contribution to the relationship's success or failure. Doing what feels good is not always the best strategy. Take care that sexual attraction plays a healthy role; resist the tendency to be dominated by cravings.",
    'focus_work': "The bottom line is important, but not all-important. Do not allow material concerns to obscure human issues. There's nothing wrong with enjoying or being compensated for good workÑbut keep the money in perspective. Know when to say, 'Enough's enough.",
    'focus_spirituality': "Many traditions position the body as bad or evil, something unclean. In your own spiritual practice, consider the wisdom of relishing the body and its spectrum of sensations. You can honor the pleasures of the body without being enslaved by them.",
    'focus_personalgrowth': "Be honest: what habit or attitude holds you back most? You might find that the qualities you most detest in others are, in fact, reflections of your darkest self. Rather than be chained to old attitudes or habits, embrace your shortcomings and strive to make more conscious choices. ",
    'focus_fortunetelling': "Adultery and unfaithfulness. A string of extremely bad luck is coming your way. Beware evil influences and wolves in sheep's clothing."
  },
  { 'name': 'The Tower',
    'imgpath': 'img/tarot-16-the-tower.jpg',
    'keywords': "Demolition, upheaval, deconstruction, disaster, destruction",
    'light': "Breaking out of old, confining habits and mindsets. Clearing the way for new growth. Dispelling the influence of an inflated ego. Getting back to basics. Stripping away harmful illusions. Receiving sudden insight.",
    'shadow': "Clinging to traditions that repress growth. Engaging in willful blindness. Rejecting evidence that change is needed. Ignoring guidance from a higher power. Maliciously engaging in destructive behavior.",
    'focus_relationships': "Extinguish old flames before they have an opportunity to dampen promising new relationships. Despite the pain involved, a clean break is healthier than a lingering, drawn-out departure. Break down the walls and communicate honestly about what's really happening.",
    'focus_work': "Sacrifice some sacred cows. Harsh criticism from above can clear ground for a new breakthrough. Something is blocking progress; identify it and boldly sweep it aside. Document everything; should the climate suddenly change, you want your ducks in a row.",
    'focus_spirituality': "Loss clears away the debris of the past, opening up new ground for new growth. As your heart opens, let old scar tissue fall away. Rather than live in fear of sudden loss, recognize that none of us owns anything. Practice detachment.",
    'focus_personalgrowth': "Identify what holds you back and attack it. Embrace bold change. Criticism may come; if so, search each barbed word for a kernel of much-needed truth. Some of life's greatest lessons are tough ones! With time, a bruised ego can become fertile ground for personal growth and maturity.",
    'focus_fortunetelling': "Impending disaster. Cancel plans and reverse decisions. Someone wants to take you down a notch or two. Don't hold back; say what you really mean. "
  },
  { 'name': 'The Star',
    'imgpath': 'img/tarot-17-the-star.jpg',
    'keywords': "Hope, optimism, openness, certainty, faith, longing, truth",
    'light': "Hoping for the best. Believing good things happen to good people. Seeing events in the best possible light. Adopting a generous spirit. Seeking guidance from above. Embracing possibility over probability.",
    'shadow': "Denying unpleasant truths. Denying personal accountability and saying, 'Things just happen!' Ignoring signs and omens. Preferring illusion to reality. Spreading pessimism and stinginess of spirit.",
    'focus_relationships': "Give freely of yourself and expect the best. Don't hold back genuine emotions; express them without shame. Consider exploring spiritual goals together. Astrology can offer important insights into compatibility. Let your honesty and openness encourage others to reveal their deepest thoughts.",
    'focus_work': "Surround yourself with visual reminders of your goal because these can serve as guiding lights when you need a way to put the situation into perspective. Expect the best of yourself and your co-workers. You'll know when the time is right to take action; have confidence in your own judgment.",
    'focus_spirituality': "Prayer and quiet time communicate your openness to guidance from above. Don't hesitate to share your spiritual side with those around you. Seek out oracles. Allow the power of spirit to flow through you; let your spirituality color all aspects of your life.",
    'focus_personalgrowth': "An optimist sees what is ... and what can be. Open yourself to possibility. Numbers never tell the whole story. Shed your ego; be yourself, no matter what others think. The only truly unique thing you have to share is the person you really are. Unmask!",
    'focus_fortunetelling': "Get an astrology chart drawn up. Someone is a little too starstruck. What's happening now has long been fore-ordained."
  },
  { 'name': 'The Moon',
    'imgpath': 'img/tarot-18-the-moon.jpg',
    'keywords': "Mystery, fantasy, imagination, dreams, uncertainty",
    'light': "Enjoying healthy fantasies and daydreams. Using your imagination. Practicing magic or celebrating the magic of everyday life. Attuning yourself to the cycles of nature. Embracing the unknown.",
    'shadow': "Becoming unable to separate fantasy from reality. Suffering from delusions. Losing your appreciation for the fantastic or magical. Adopting a ruthlessly logical mindset. Failing to appreciate life's mysteries.",
    'focus_relationships': "Moonlight becomes you, so don't be afraid to indulge in a little romantic lunacy. Navigating your way to a fulfilling relationship involves risks. Some people will say you're crazy. Pay attention to your instincts, surround yourself with loyal guides, and make your move.",
    'focus_work': "Avoid linear/logical approaches and go with your gut. Brainstorm. Put the rules aside and use your imagination. What would happen if restrictions were removed? What might happen? What could happen? A little lunacy can be a good thing; blow off steam, change your habits, and try working in a different light.",
    'focus_spirituality': "How does your personal spiritual path incorporate the Divine Feminine? What qualities would a divine mother offer? Which aspects of your personal spirituality would benefit from a feminine touch? How might contact with the divine feminine benefit you today? How might you honor or invite that energy?",
    'focus_personalgrowth': "Faced with an uncertain future, you might feel led to abandon your search for self and crawl back into your shell. You can move forward without tossing caution to the wind. Uncertainty can be the mother of great creativity. Listen your instincts, clarify your path, and keep going.",
    'focus_fortunetelling': "Watch for problems at the end of the month. Someone you know needs to howl at the moon more often. Someone is about to change his or her mind about an important decision."
  },
  { 'name': 'The Sun',
    'imgpath': 'img/tarot-19-the-sun.jpg',
    'keywords': "Joy, brilliance, validation, attention, energy",
    'light': "Seeing things clearly. Experiencing intense joy. Celebrating your own successes. Knowing you're good at what you do. Gaining recognition for your personal genius.",
    'shadow': "Being dazzled by your own accomplishments. Becoming absorbed in your own self-image. Feeling rushed and distracted. Exerting yourself to the point of exhaustion. Overstating your abilities or misrepresenting your achievements.",
    'focus_relationships': "You're turning heads without realizing it. Attention is coming your wayÑand you deserve it! The admiration of others is a warm glow, so bask in it while you can. As all things begin to revolve around you, take care you don't get blinded or burned by your own brilliance.",
    'focus_work': "With the proper strategy, you're all set to be the golden boy (or girl). Approval and praise are the order of the day. Accept all this admiration with humbleness; give credit where credit's due. Meanwhile, make hay while the sun shines. Remember: after noon, the rest of the day is a sunset!",
    'focus_spirituality': "As your meditative and spiritual practices hone your sensitivities, you begin to feel your connectedness to the energies around you. Branch out. Spread warmth, love, and joy through your attitudes and actions. Today, embody the universal light.",
    'focus_personalgrowth': "Learn to win gracefully. Accept compliments with a humble heart. You can acknowledge and celebrate your own achievements without falling prey to greediness. Be who you are. You've earned this moment, but don't let pride in your progress hinder further growth!",
    'focus_fortunetelling': "Everything's coming up roses (or sunflowers, whatever the case may be). Whatever's on your mind, go for it because you can't lose today."
  },
  { 'name': 'Judgement',
    'imgpath': 'img/tarot-20-judgement.jpg',
    'keywords': "Revival, renewal, resurrection, evaluation, invitation",
    'light': "Receiving a wake-up call. Discovering a new purpose in life. Becoming totally and completely yourself. Receiving a well-deserved reward. Passing an evaluation or examination. Welcoming the start of a new phase of life.",
    'shadow': "Being weighed in the balances and found wanting. Failing to measure up to a well-defined standard. Being caught goofing off or misbehaving. Failing to prepare for an examination you know is coming. Rejecting an opportunity to reinvent yourself.",
    'focus_relationships': "Freshen your relationship by taking advantage of opportunities to reinvent yourself (and each other). Swap roles. Seek out entertainment you would normally avoid. Shatter habits and breath new life into your partnerships. What you learn in the process could be a wake-up call for you both.",
    'focus_work': "If something or someone is holding you back, it's time for a Come to Jesus Meeting -- a time to air dirty laundry, read someone the riot act, or say out loud what, to this point, has only been said in private. Identify the problem and eliminate it before the decay spreads to other efforts. If things are going well, use this as an opportunity to define why, so you can replicate your success elsewhere.",
    'focus_spirituality': "With a shock, we realize the impermanent nature of this world. Use this sudden insight to your advantage. Answer the trumpet call and reinvent yourself by refusing to cling to distractions. Set aside your stumbling blocks and embrace transformation.",
    'focus_personalgrowth': "The assessments of others cannot impact your true value. The only standard you must meet is being the very best version of yourself you can be. Identify your next steps ... and take them. Don't do this for others; do it for you.",
    'focus_fortunetelling': "An old issue you thought was over will come up again today. Get ready for huge changes: break-ups, sudden calls from old friends, and unexpected setbacks. God's trying to get your attention."
  },
  { 'name': 'The World',
    'imgpath': 'img/tarot-21-the-world.jpg',
    'keywords': "Wholeness, integration, totality, completeness, fullness",
    'light': "Having it all. Knowing and loving yourself as completely as possible. Seeing the interconnection of all things and people. Enhancing your perspective. Living life to its fullest. Understanding the meaning of life.",
    'shadow': "Allowing greed and envy to prevent you from enjoying what you do possess. Failing to see the larger design in ordinary events. Believing that everything that exists can be touched, counted, or measured. Failing to see the divine reflected in those around you.",
    'focus_relationships': "With mutual trust and effort, very different people can come together to create a reality greater than the sum of its parts. Once you have a taste of what can be, settling for less will be difficult. Keep in mind, though, that a dream of perfection can foster dissatisfaction with an otherwise perfectly good relationship.",
    'focus_work': "Synergy! It's possible for everyone involved to work together in harmony to create something better than any one person could produce on his or her own. Encourage people to share ideas. Allow others to share in the investmentÑand the glory. Unite and meet your goals.",
    'focus_spirituality': "Enlightenment is a goal; reaching it is bliss. Rather than beat yourself up for falling short, celebrate your progress. Meantime, keep in mind the lesson of the Tarot: Even as we reach one level of enlightenment, we become a fool again.",
    'focus_personalgrowth': "For most challenges, both intuitive and logical approaches exist. Most of us favor one over the other, but the secret to true mastery involves learning to wield both with perfect facility. Identify your least favorite approach, and then speed your growth by giving it special attention.",
    'focus_fortunetelling': "Winning the lottery. Getting your heart's desire. Having everything you ever imagined having."
  }
]

