export const cards = [
  { 'name': 'Ace of Cups', 'imgpath': 'img/cups01.jpg'},
  { 'name': 'Two of Cups', 'imgpath': 'img/cups02.jpg'},
  { 'name': 'Three of Cups', 'imgpath': 'img/cups03.jpg'},
  { 'name': 'Four of Cups', 'imgpath': 'img/cups04.jpg'},
  { 'name': 'Five of Cups', 'imgpath': 'img/cups05.jpg'},
  { 'name': 'Six of Cups', 'imgpath': 'img/cups06.jpg'},
  { 'name': 'Seven of Cups', 'imgpath': 'img/cups07.jpg'},
  { 'name': 'Eight of Cups', 'imgpath': 'img/cups08.jpg'},
  { 'name': 'Nine of Cups', 'imgpath': 'img/cups09.jpg'},
  { 'name': 'Ten of Cups', 'imgpath': 'img/cups10.jpg'},
  { 'name': 'Page of Cups', 'imgpath': 'img/cups11.jpg'},
  { 'name': 'Knight of Cups', 'imgpath': 'img/cups12.jpg'},
  { 'name': 'Queen of Cups', 'imgpath': 'img/cups13.jpg'},
  { 'name': 'King of Cups', 'imgpath': 'img/cups14.jpg'},
  { 'name': 'Ace of Swords', 'imgpath': 'img/swords01.jpg'},
  { 'name': 'Two of Swords', 'imgpath': 'img/swords02.jpg'},
  { 'name': 'Three of Swords', 'imgpath': 'img/swords03.jpg'},
  { 'name': 'Four of Swords', 'imgpath': 'img/swords04.jpg'},
  { 'name': 'Five of Swords', 'imgpath': 'img/swords05.jpg'},
  { 'name': 'Six of Swords', 'imgpath': 'img/swords06.jpg'},
  { 'name': 'Seven of Swords', 'imgpath': 'img/swords07.jpg'},
  { 'name': 'Eight of Swords', 'imgpath': 'img/swords08.jpg'},
  { 'name': 'Nine of Swords', 'imgpath': 'img/swords09.jpg'},
  { 'name': 'Ten of Swords', 'imgpath': 'img/swords10.jpg'},
  { 'name': 'Page of Swords', 'imgpath': 'img/swords11.jpg'},
  { 'name': 'Knight of Swords', 'imgpath': 'img/swords12.jpg'},
  { 'name': 'Queen of Swords', 'imgpath': 'img/swords13.jpg'},
  { 'name': 'King of Swords', 'imgpath': 'img/swords14.jpg'},
  { 'name': 'Ace of Wands', 'imgpath': 'img/wands01.jpg'},
  { 'name': 'Two of Wands', 'imgpath': 'img/wands02.jpg'},
  { 'name': 'Three of Wands', 'imgpath': 'img/wands03.jpg'},
  { 'name': 'Four of Wands', 'imgpath': 'img/wands04.jpg'},
  { 'name': 'Five of Wands', 'imgpath': 'img/wands05.jpg'},
  { 'name': 'Six of Wands', 'imgpath': 'img/wands06.jpg'},
  { 'name': 'Seven of Wands', 'imgpath': 'img/wands07.jpg'},
  { 'name': 'Eight of Wands', 'imgpath': 'img/wands08.jpg'},
  { 'name': 'Nine of Wands', 'imgpath': 'img/wands09.jpg'},
  { 'name': 'Ten of Wands', 'imgpath': 'img/wands10.jpg'},
  { 'name': 'Page of Wands', 'imgpath': 'img/wands11.jpg'},
  { 'name': 'Knight of Wands', 'imgpath': 'img/wands12.jpg'},
  { 'name': 'Queen of Wands', 'imgpath': 'img/wands13.jpg'},
  { 'name': 'King of Wands', 'imgpath': 'img/wands14.jpg'},
  { 'name': 'Ace of Pentacles', 'imgpath': 'img/pents01.jpg'},
  { 'name': 'Two of Pentacles', 'imgpath': 'img/pents02.jpg'},
  { 'name': 'Three of Pentacles', 'imgpath': 'img/pents03.jpg'},
  { 'name': 'Four of Pentacles', 'imgpath': 'img/pents04.jpg'},
  { 'name': 'Five of Pentacles', 'imgpath': 'img/pents05.jpg'},
  { 'name': 'Six of Pentacles', 'imgpath': 'img/pents06.jpg'},
  { 'name': 'Seven of Pentacles', 'imgpath': 'img/pents07.jpg'},
  { 'name': 'Eight of Pentacles', 'imgpath': 'img/pents08.jpg'},
  { 'name': 'Nine of Pentacles', 'imgpath': 'img/pents09.jpg'},
  { 'name': 'Ten of Pentacles', 'imgpath': 'img/pents10.jpg'},
  { 'name': 'Page of Pentacles', 'imgpath': 'img/pents11.jpg'},
  { 'name': 'Knight of Pentacles', 'imgpath': 'img/pents12.jpg'},
  { 'name': 'Queen of Pentacles', 'imgpath': 'img/pents13.jpg'},
  { 'name': 'King of Pentacles', 'imgpath': 'img/pents14.jpg'},
  { 'name': 'The Fool', 'imgpath': 'img/tarot-0-fool.jpg'},
  { 'name': 'The Magician', 'imgpath': 'img/tarot-1-magician.jpg'},
  { 'name': 'The High Priestess', 'imgpath': 'img/tarot-2-high-priestess.jpg'},
  { 'name': 'The Empress', 'imgpath': 'img/tarot-3-the-empress.jpg'},
  { 'name': 'The Emperor', 'imgpath': 'img/tarot-4-the-emperor.jpg'},
  { 'name': 'The Hierophant', 'imgpath': 'img/tarot-5-the-hierophant.jpg'},
  { 'name': 'The Lovers', 'imgpath': 'img/tarot-6-the-lovers.jpg'},
  { 'name': 'The Chariot', 'imgpath': 'img/tarot-7-the-chariot.jpg'},
  { 'name': 'Strength', 'imgpath': 'img/tarot-8-strength.jpg'},
  { 'name': 'The Hermit', 'imgpath': 'img/tarot-9-hermit.jpg'},
  { 'name': 'Wheel of Fortune', 'imgpath': 'img/tarot-10-wheel-of-fortune.jpg'},
  { 'name': 'Justice', 'imgpath': 'img/tarot-11-justice.jpg'},
  { 'name': 'The Hanged Man', 'imgpath': 'img/tarot-12-the-hanged-man.jpg'},
  { 'name': 'Death', 'imgpath': 'img/tarot-13-death.jpg'},
  { 'name': 'Temperance', 'imgpath': 'img/tarot-14-temperance.jpg'},
  { 'name': 'The Devil', 'imgpath': 'img/tarot-15-the-devil.jpg'},
  { 'name': 'The Tower', 'imgpath': 'img/tarot-16-the-tower.jpg'},
  { 'name': 'The Star', 'imgpath': 'img/tarot-17-the-star.jpg'},
  { 'name': 'The Moon', 'imgpath': 'img/tarot-18-the-moon.jpg'},
  { 'name': 'The Sun', 'imgpath': 'img/tarot-19-the-sun.jpg'},
  { 'name': 'Judgement', 'imgpath': 'img/tarot-20-judgement.jpg'},
  { 'name': 'The World', 'imgpath': 'img/tarot-21-the-world.jpg'}
]

